### ISSUE TITLE
advanced solidity concepts progress lost ( completed 3-4 exercises and now its showing 0% ). #45

### ISSUE THREAD

**Issue by Maxmos1124** [Maxmos1124/zombies-examples#20]
I just logged in from a different device in my Cryptozombies account it's showing that I have 0% progress in the advanced solidity concepts chapter which I am completely certain that I completed at least 3-4 exercises.

**Comment by Maxmos1124** [comment]
also, the website sometimes does not load the next chapter once the current exercise has been completed. you have to go to the homepage and then open the next exercise.

**Comment by juddydev** [comment]
I can confirm that this is an annoying problem of crypto zombies. (still as of July 5th 2023). I use chrome browser.
